config/routes.rb
Rails.application.routes.draw do
  resources :campaigns do
    resources :donations
    resources :comments
  end
  resources :donations
  resources :campaigns
  devise_for :users
  get 'pages/profile'
  get 'pages/index'
  get 'pages/dashboard'
  get 'campaigns/like'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user
  before_save :default_values

  has_attached_file :avatar, styles: { medium: "100x100>", thumb: "50x50" }, default_url: "https://hipgive.org/wp-content/uploads/2016/07/Vector_Donate_Icon_3.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :donations, dependent: :destroy
  has_many :comments

  validates :title, presence: true
  validates :review, presence: true, length: {maximum: 20}
  validates :description, presence: true, length: {maximum: 30}
  validates :goal, presence: true,numericality: { greater_than_or_equal_to: 500 }
  validates :category, presence: true

  scope :ongoing, -> {where(["finalized_in >= ?", DateTime.now.to_date])}
  scope :popular, -> {ongoing.order(likes: :desc)}

  def default_values
    self.likes ||= 0
  end

  def like(id_cam)
    @campaign = Campaign.find(id_cam)
    @campaign.increment!(:likes, 1)
  end

  def collection(id_camp)
    @donation = Donation.where(:campaign_id => id_camp)
    total = 0
    @donation.each do |donation|
      total = donation.amount + total
    end
    return total
  end

  def progress(id_camp)
    @campaign = Campaign.find(id_camp)
    amout = @campaign.goal
    return collection(id_camp)/amout*100
  end

  CATEGORIES = ['EDUCATION','SPORTS','MEDICINE', 'FOOD','PETS']
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :autor, presence: true, length: {maximum: 15}
  validates :message, presence: true, length: {maximum: 30}

  belongs_to :campaign
end

app/models/donation.rb
class Donation < ApplicationRecord
  validates :autor, presence: true, length: {maximum: 15}
  validates :message, presence: true, length: {maximum: 30}
  validates :amount, presence: true,numericality: { greater_than_or_equal_to: 0}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50" }, default_url: "https://image.freepik.com/iconos-gratis/simbolo-de-usuario-desconocido_318-54178.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
  has_many :campaigns
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:city,:country,:receive_emails])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name,:city,:country,:receive_emails,:avatar])
    end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:new]
  # GET /campaigns run -p port:2 -it my-py-app
  # GET /campaigns.json cd tarea && python main.py
  def index
    @campaigns = Campaign.all.order(created_at: :asc)
    @campaignsEdu = Campaign.popular.where(:category => "EDUCATION").order(created_at: :asc)
    @campaignsSpr = Campaign.popular.where(:category => "SPORTS").order(created_at: :asc)
    @campaignsMed = Campaign.popular.where(:category => "MEDICINE").order(created_at: :asc)
    @campaignsFoo = Campaign.popular.where(:category => "FOOD").order(created_at: :asc)
    @campaignsPet = Campaign.popular.where(:category => "PETS").order(created_at: :asc)
  end

  def show
    @campaign = Campaign.find(params[:id])
    @donation = Donation.new
    @comment = Comment.new
    @donations = @campaign.donations
    @comments = @campaign.comments
  end

  def like
     @campaign = Campaign.find(params[:id])
     @campaign.like(@campaign.id)
  end

  def new
    @campaign = Campaign.new
  end

  def edit
  end

  def create
    @campaign = current_user.campaigns.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @campaign.update(mod_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    def campaign_params
      params.require(:campaign).permit(:title, :description, :review, :goal, :category,:finalized_in,:avatar)
    end

    def mod_params
      params.require(:campaign).permit(:title, :description, :review, :category,:avatar)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @campaign = Campaign.find(params[:campaign_id])
        @comment = @campaign.comments.create(comment_params)
        redirect_to @campaign
    end

    private
        def comment_params
            params.require(:comment).permit(:autor,:message)
        end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  def create
    @campaign = Campaign.find(params[:campaign_id])
    @donation = @campaign.donations.create(donation_params)
    redirect_to @campaign
  end

  private
    def donation_params
      params.require(:donation).permit(:autor,:message,:amount)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @campaigns = Campaign.ongoing.order(created_at: :desc)
  end

  def profile
  end

  def dashboard
    @campaigns = current_user.campaigns.ongoing.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/campaigns/_form.html.erb
<%= form_for(campaign) do |f| %>
    <% if @campaign.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@campaign.errors.count, "error") %> have prevented the book from being recorded
          </h2>
          <ul>
            <% @campaign.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="row">
      <div class="col s12 m6">
        <div class="card white darken-1">
          <div class="card-content black-text">
            <span class="card-title">Sign up</span>
            <div class="field">
              <%= f.label :title %>
              <%= f.text_field :title %>
            </div>

            <div class="field">
              <%= f.label :description %>
              <%= f.text_field :description %>
            </div>

            <div class="field">
              <%= f.label :review %>
              <%= f.text_area :review %>
            </div>

            <div class="field">
              <%= f.label :category %>
              <%= f.select :category , options_for_select([["Education", "e"], ["Medicine", "m"]])%>
            </div>

            <div class="actions">
              <%= f.submit "Save", class:"waves-effect waves-light btn" %>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

<script>
    $('.datepicker').pickadate({
        selectMonths: true, // Creates a dropdown to control month
        selectYears: 15 // Creates a dropdown of 15 years to control year
    });
</script>

app/views/campaigns/dashboard.html.erb
<h1>Welcome to your dashboard</h1>

app/views/campaigns/edit.html.erb
<h1>Editing Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/campaigns/index.html.erb
<div class="row">
  <div class="col s12">
    <ul class="tabs">
      <li class="tab col s2"><a href="#test1">ALL</a></li>
      <li class="tab col s2"><a href="#test2">EDUCATION</a></li>
      <li class="tab col s2"><a href="#test3">SPORT</a></li>
      <li class="tab col s2"><a href="#test4">MEDICINE</a></li>
      <li class="tab col s2"><a href="#test5">FOOD</a></li>
      <li class="tab col s2"><a href="#test6">PETS</a></li>
    </ul>
  </div>
  <div id="test1" class="col m12">
      <div class="row">
        <% @campaigns.each do |campaign| %>
            <% if campaign.goal>=campaign.collection(campaign.id)  %>
              <div class="col s4">
                  <div class="card">
                    <div class="card-image waves-effect waves-block waves-light">
                      <%= image_tag campaign.avatar.url(:medium),class: "size" %>
                    </div>
                    <div class="card-content">
                      <center>
                        <span class="card-title activator grey-text text-darken-4"><%= campaign.title %><i class="material-icons right">more_vert</i></span>
                      </center>
                      <%= link_to 'View',campaign,class:"modal-action modal-close modal-action waves-effect waves-light btn" %>
                    </div>
                    <div class="card-reveal">
                      <span class="card-title grey-text text-darken-4"><%= campaign.title %><i class="material-icons right">close</i></span>
                      <p>Goal: <%= campaign.goal %></p>
                      <p>Collection</p>
                      <div class="progress">
                        <div class="determinate" style="width: <%= campaign.progress(campaign.id) %>%"></div>
                      </div>
                      <p>Created at: <%= campaign.created_at %></p>
                      <p>Created by: <%= campaign.user.name %></p>
                    </div>
                  </div>
                </div>
            <% end %>
        <% end %>
      </div>
  </div>
  <div id="test2" class="col m12">
        <div class="row">
          <% @campaignsEdu.each do |campaign| %>
              <% if campaign.goal>=campaign.collection(campaign.id)  %>
                <div class="col s4">
                    <div class="card">
                      <div class="card-image waves-effect waves-block waves-light">
                        <%= image_tag campaign.avatar.url(:medium),class: "size" %>
                      </div>
                      <div class="card-content">
                        <center>
                          <span class="card-title activator grey-text text-darken-4"><%= campaign.title %><i class="material-icons right">more_vert</i></span>
                        </center>
                        <%= link_to 'View',campaign,class:"modal-action modal-close modal-action waves-effect waves-light btn" %>
                      </div>
                      <div class="card-reveal">
                        <span class="card-title grey-text text-darken-4"><%= campaign.title %><i class="material-icons right">close</i></span>
                        <p>Goal: <%= campaign.goal %></p>
                        <p>Collection</p>
                        <div class="progress">
                          <div class="determinate" style="width: <%= campaign.progress(campaign.id) %>%"></div>
                        </div>
                        <p>Created at: <%= campaign.created_at %></p>
                        <p>Created by: <%= campaign.user.name %></p>
                      </div>
                    </div>
                </div>
              <% end %>
          <% end %>
        </div>
  </div>
  <div id="test3" class="col m12">
        <div class="row">
          <% @campaignsSpr.each do |campaign| %>
              <% if campaign.goal>=campaign.collection(campaign.id)  %>
                <div class="col s4">
                    <div class="card">
                      <div class="card-image waves-effect waves-block waves-light">
                      <%= image_tag campaign.avatar.url(:medium),class: "size" %>
                      </div>
                      <div class="card-content">
                        <center>
                          <span class="card-title activator grey-text text-darken-4"><%= campaign.title %><i class="material-icons right">more_vert</i></span>
                        </center>
                        <%= link_to 'View',campaign,class:"modal-action modal-close modal-action waves-effect waves-light btn" %>
                      </div>
                      <div class="card-reveal">
                        <span class="card-title grey-text text-darken-4"><%= campaign.title %><i class="material-icons right">close</i></span>
                        <p>Goal: <%= campaign.goal %></p>
                        <p>Collection</p>
                        <div class="progress">
                          <div class="determinate" style="width: <%= campaign.progress(campaign.id) %>%"></div>
                        </div>
                        <p>Created at: <%= campaign.created_at %></p>
                        <p>Created by: <%= campaign.user.name %></p>
                      </div>
                    </div>
                </div>
              <% end %>
          <% end %>
        </div>
  </div>
  <div id="test4" class="col m12">
        <div class="row">
          <% @campaignsMed.each do |campaign| %>
              <% if campaign.goal>=campaign.collection(campaign.id)  %>
                <div class="col s4">
                    <div class="card">
                      <div class="card-image waves-effect waves-block waves-light">
                      <%= image_tag campaign.avatar.url(:medium),class: "size" %>
                      </div>
                      <div class="card-content">
                        <center>
                          <span class="card-title activator grey-text text-darken-4"><%= campaign.title %><i class="material-icons right">more_vert</i></span>
                        </center>
                        <%= link_to 'View',campaign,class:"modal-action modal-close modal-action waves-effect waves-light btn" %>
                      </div>
                      <div class="card-reveal">
                        <span class="card-title grey-text text-darken-4"><%= campaign.title %><i class="material-icons right">close</i></span>
                        <p>Goal: <%= campaign.goal %></p>
                        <p>Collection</p>
                        <div class="progress">
                          <div class="determinate" style="width: <%= campaign.progress(campaign.id) %>%"></div>
                        </div>
                        <p>Created at: <%= campaign.created_at %></p>
                        <p>Created by: <%= campaign.user.name %></p>
                      </div>
                    </div>
                </div>
              <% end %>
          <% end %>
        </div>
  </div>
  <div id="test5" class="col m12">
        <div class="row">
          <% @campaignsFoo.each do |campaign| %>
              <% if campaign.goal>=campaign.collection(campaign.id)  %>
                <div class="col s4">
                    <div class="card">
                      <div class="card-image waves-effect waves-block waves-light">
                      <%= image_tag campaign.avatar.url(:medium),class:"size" %>
                      </div>
                      <div class="card-content">
                        <center>
                          <span class="card-title activator grey-text text-darken-4"><%= campaign.title %><i class="material-icons right">more_vert</i></span>
                        </center>
                        <%= link_to 'View',campaign,class:"modal-action modal-close modal-action waves-effect waves-light btn" %>
                      </div>
                      <div class="card-reveal">
                        <span class="card-title grey-text text-darken-4"><%= campaign.title %><i class="material-icons right">close</i></span>
                        <p>Goal: <%= campaign.goal %></p>
                        <p>Collection</p>
                        <div class="progress">
                          <div class="determinate" style="width: <%= campaign.progress(campaign.id) %>%"></div>
                        </div>
                        <p>Created at: <%= campaign.created_at %></p>
                        <p>Created by: <%= campaign.user.name %></p>
                      </div>
                    </div>
                </div>
              <% end %>
          <% end %>
        </div>
  </div>
  <div id="test6" class="col m12">
        <div class="row">
          <% @campaignsPet.each do |campaign| %>
              <% if campaign.goal>=campaign.collection(campaign.id)  %>
                <div class="col s4">
                  <div class="card">
                    <div class="card-image waves-effect waves-block waves-light">
                    <%= image_tag campaign.avatar.url(:medium),class: "size" %>
                    </div>
                    <div class="card-content">
                      <center>
                        <span class="card-title activator grey-text text-darken-4"><%= campaign.title %><i class="material-icons right">more_vert</i></span>
                      </center>
                      <i><%= link_to 'visibility',campaign,class:"material-icons modal-action modal-close modal-action waves-effect waves-light btn" %></i>
                    </div>
                    <div class="card-reveal">
                      <span class="card-title grey-text text-darken-4"><%= campaign.title %><i class="material-icons right">close</i></span>
                      <p>Goal: <%= campaign.goal %></p>
                      <p>Collection</p>
                      <div class="progress">
                        <div class="determinate" style="width: 70%"></div>
                      </div>
                      <p>Created at: <%= campaign.created_at %></p>
                      <p>Created by: <%= campaign.user.name %></p>
                    </div>
                  </div>
                </div>
              <% end %>
          <% end %>
        </div>
  </div>
</div>

app/views/campaigns/new.html.erb
<div class="row center-block">
  <div class="col s12">
    <div class="card white darken-1">
      <div class="card-content black-text">
        <span class="card-title">Create a campaign</span>
        <%= form_for :campaign, url: campaigns_path do |f| %>
            <div class="field">
              <%= f.label :title %>
              <%= f.text_field :title%>
            </div>

            <div class="field">
              <%= f.label :description %>
              <%= f.text_field :description %>
            </div>

            <div class="field">
              <%= f.label :review %>
              <%= f.text_area :review%>
            </div>

            <div class="field">
              <%= f.label :goal %>
              <%= f.text_field :goal %>
            </div>

            <div class="field">
              <%= f.label :category %>
              <%= f.collection_select :category, Campaign::CATEGORIES, :to_s, :to_s, :include_blank => FALSE, class:"dropdown-button btn"%>
            </div>

            <div class="field">
              <%= f.label :finalized_in %>
              <%= f.text_field :finalized_in, class:"datepicker" %>
            </div>

            <div class="field">
            <p>Photo:</p>
              <%= f.file_field :avatar %>
            </div>

            <div class="actions">
              <%= f.submit "Start it", class:"waves-effect waves-light btn" %>
            </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
<script>
    $('.datepicker').pickadate({
        selectMonths: true, // Creates a dropdown to control month
        selectYears: 15 // Creates a dropdown of 15 years to control year
    });
    $('.dropdown-button').dropdown('open');
    $('.dropdown-button').dropdown('close');
</script>

app/views/layouts/_navbar1.html.erb
<nav>
  <div class="nav-wrapper">
    <%= link_to "GoFundMe", root_path, class: "brand-logo" %>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%=	link_to "CAMPAIGNS" %></li>
      <li><%=	link_to "SIGN IN" %></li>
      <li><%=	link_to "LOGIN", new_user_session_path %></li>
      <li><%=	link_to "CONTACT US",new_user_registration_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoFundMe</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
  <% if current_user %>
      <nav>
        <div class="nav-wrapper">
          <%= link_to "GoFundMe", root_path, class: "brand-logo logo" %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><%=	link_to "CAMPAIGNS",campaigns_path %></li>
            <li><%=	link_to "STAR A CAMPAIGN",new_campaign_path %></li>
            <li><%=	link_to "DASHBOARD",pages_dashboard_path %></li>
            <li><a class="dropdown-button" href="#" data-activates="dropdown1"><%= current_user.email %><i class="material-icons right">arrow_drop_down</i></a></li>
            <%= image_tag current_user.avatar.url(:thumb), class:"circle responsive-img"%>
            <ul id="dropdown1" class="dropdown-content">
              <li><%=	link_to "PROFILE",pages_profile_path%></li>
              <li><%=	link_to "LOGOUT", destroy_user_session_path, method: :delete %></li>
            </ul>
          </ul>
        </div>
      </nav>
  <% else %>
      <nav>
        <div class="nav-wrapper">
          <%= link_to "GoFundMe", root_path, class: "brand-logo" %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><%=	link_to "CAMPAIGNS",campaigns_path %></li>
            <li><%=	link_to "SIGN IN",new_user_registration_path %></li>
            <li><%=	link_to "LOGIN", new_user_session_path %></li>
            <li><%=	link_to "CONTACT US" %></li>
          </ul>
        </div>
      </nav>
  <% end %>
  
  <main class="light-blue lighten-5">
  <div class="container ">
    <% if notice %>
        <p class="alert alert-success">
            <script>
                $(function() {
                  Materialize.toast("<%= notice %>", 3000);
                });
            </script>
        </p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger">
            <script>
                $(function() {
                  Materialize.toast("<%= alert %>", 3000);
                });
            </script>
        </p>
    <% end %>
    <%= yield %>

    </main>
  </div>
  <footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Team</h5>
          <p class="grey-text text-lighten-4">Luis - Marcial </p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Tools</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="http://materializecss.com/">Materialize</a></li>
            <li><a class="grey-text text-lighten-3" href="https://github.com/plataformatec/devise">Devise</a></li>
            <li><a class="grey-text text-lighten-3" href="https://rubygems.org/">RubyGems.org</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
        © 2017 Unitec
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>Welcome to your Dashboard</h1>
<div class="divider"></div>
<div class="row">
  <% @campaigns.each do |campaign| %>
      <% if campaign.goal>=campaign.collection(campaign.id)  %>
        <div class="col m4">
              <div class="card">
                <div class="card-image waves-effect waves-block waves-light">
                    <%= image_tag campaign.avatar.url(:medium),class: "size" %>
                </div>
                <div class="card-content">
                  <center>
                    <span class="card-title activator grey-text text-darken-4"><%= campaign.title %><i class="material-icons right">more_vert</i></span>
                  </center>
                  <%= link_to 'View',campaign,class:"modal-action modal-close modal-action waves-effect waves-light btn" %>
                </div>
                <div class="card-reveal">
                  <span class="card-title grey-text text-darken-4"><%= campaign.title %><i class="material-icons right">close</i></span>
                  <p>Goal: <%= campaign.goal %></p>
                  <p>Collection</p>
                  <div class="progress">
                    <div class="determinate" style="width: <%= campaign.progress(campaign.id) %>%"></div>
                  </div>
                  <p>Created at: <%= campaign.created_at %></p>
                  <p>Created by: <%= campaign.user.name %></p>
                </div>
              </div>
        </div>
      <% end %>
  <% end %>
</div>

app/views/pages/index.html.erb
<div class="carousel carousel-slider center" data-indicators="true">
    <div class="carousel-fixed-item center">
      <div class="col m12">
        <div class="col m6">
          <%= link_to "Star a Campaign", new_campaign_path,class:"modal-action modal-close modal-action waves-effect waves-light btn"%>
        </div>
      </div>
    </div>
    <div class="carousel-item white-text" href="#one!">
<%= image_tag("slider/2.jpg", class:"silider")%>
      <h2 class="white text">First Panel</h2>
      <p class="white-text">This is your first panel</p>      
    </div>
    <div class="carousel-item amber white-text" href="#two!">
<%= image_tag("slider/as.jpg", class:"silider")%>
      <h2 class="white text">Second Panel</h2>
      <p class="white-text">This is your second panel</p>
    </div>
    <div class="carousel-item green white-text" href="#three!">
<%= image_tag("slider/3.jpg", class:"silider")%>
      <h2 class="white text">Third Panel</h2>
      <p class="white-text">This is your third panel</p>
    </div>
    <div class="carousel-item blue white-text" href="#four!">
<%= image_tag("slider/4.jpg", class:"silider")%>   
      <h2 class="white text">Fourth Panel</h2>
      <p class="white-text">This is your fourth panel</p>
    </div>
  </div>

<div class="divider"></div>
<div class="row">
  <% @campaigns.each do |campaign| %>
      <% if campaign.goal>=campaign.collection(campaign.id)  %>
        <div class="col s12 m4">
              <div class="card">
                <div class="card-image waves-effect waves-block waves-light">
                <%= image_tag campaign.avatar.url(:medium),class:"size" %>
                </div>
                <div class="card-content">
                  <center>
                    <span class="card-title activator grey-text text-darken-4"><%= campaign.title %><i class="material-icons right">more_vert</i></span>
                  </center>
                  <%= link_to 'View',campaign,class:"modal-action modal-close modal-action waves-effect waves-light btn" %>
                </div>
                <div class="card-reveal">
                  <span class="card-title grey-text text-darken-4"><%= campaign.title %><i class="material-icons right">close</i></span>
                  <p>Goal: <%= campaign.goal %></p>
                  <p>Collection</p>
                  <div class="progress">
                    <div class="determinate" style="width: <%= campaign.progress(campaign.id) %>%"></div>
                  </div>
                  <p>Created at: <%= campaign.created_at %></p>
                  <p>Created by: <%= campaign.user.name %></p>
                </div>
              </div>
        </div>
      <% end %>
  <% end %>
</div>

<script>
    $('.carousel.carousel-slider').carousel({fullWidth: true});

 $('.carousel.carousel-slider').carousel();
  setInterval(function() {
    $('.carousel').carousel('next');
  }, 3000);
</script>

app/views/pages/profile.html.erb
<h1>Personal Information</h1>
<div class="divider"></div>
<div class="container">
<body>

  <h5>Name:    <%= current_user.name %></h5>
  <h5>Email:   <%= current_user.email %></h5>
  <h5>City:    <%= current_user.city %></h5>
  <h5>Country: <%= current_user.country %></h5>
  <h5>Receive: <%= current_user.receive_emails %></h5>
  <center>
  <%=	link_to "Edit", edit_user_registration_path, class: "waves-effect waves-light btn" %>
</center>
</body>
</div>